# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wnioski', '0001_initial'),
        ('auth_ex', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obiekty', models.ManyToManyField(to='wnioski.Obiekt')),
                ('pracownicy', models.ManyToManyField(to='auth_ex.Pracownik')),
            ],
        ),
    ]
