# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wnioski', '0001_initial'),
        ('auth_ex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('uprawnienia', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Wgląd'), ('2', 'Tworzenie'), ('3', 'Modyfikacja'), ('4', 'Przetwarzanie na serwerze i w biurze'), ('5', 'Przechowywanie'), ('6', 'Usuwanie, niszczenie'), ('7', 'Udostępnianie, powierzanie, przesyłanie')], max_length=25, verbose_name='Uprawnienia')),
                ('key', models.CharField(blank=True, max_length=10, verbose_name='Klucz')),
                ('typ_wniosku', models.CharField(choices=[('1', 'Nadanie uprawnień'), ('2', 'Odebranie uprawnień')], max_length=10, verbose_name='Typ')),
                ('obiekty', models.ManyToManyField(blank=True, to='wnioski.Obiekt')),
                ('pracownicy', models.ManyToManyField(blank=True, to='auth_ex.Pracownik')),
            ],
        ),
    ]
