# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial_squashed_0005_auto_20171228_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='key',
            field=models.CharField(blank=True, max_length=10, verbose_name='Klucz'),
        ),
        migrations.AddField(
            model_name='cart',
            name='typ_wniosku',
            field=models.CharField(choices=[('1', 'Nadanie uprawnień'), ('2', 'Odebranie uprawnień'), ('3', 'Zmiana uprawnień')], default='', max_length=10, verbose_name='Typ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='uprawnienia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Wgląd'), ('2', 'Tworzenie'), ('3', 'Modyfikacja'), ('4', 'Przetwarzanie na serwerze i w biurze'), ('5', 'Przechowywanie'), ('6', 'Usuwanie, niszczenie'), ('7', 'Udostępnianie, powierzanie, przesyłanie')], max_length=25, verbose_name='Uprawnienia'),
        ),
    ]
