# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-28 14:11
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20171228_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='uprawnienia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Wgląd'), ('2', 'Tworzenie'), ('3', 'Modyfikacja'), ('4', 'Przetwarzanie na serwerze i w biurze'), ('5', 'Przechowywanie'), ('6', 'Usuwanie, niszczenie'), ('7', 'Udostępnianie, powierzanie, przesyłanie')], default='1', max_length=1, verbose_name='Uprawnienia'),
        ),
    ]
