# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obiekty_chronione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=40)),
                ('typ', models.CharField(max_length=30)),
                ('jedn_org', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wnioski',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zlo', models.DateTimeField(verbose_name='date published')),
                ('id_obiektu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Obiekty_chronione')),
                ('id_prac_dot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Pracownicy')),
            ],
        ),
    ]
