# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0001_initial'),
        ('wnioski', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministratorObiektu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktywny', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('obiekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wnioski.Obiekt')),
                ('pracownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_ex.Pracownik')),
            ],
        ),
    ]
