# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wnioski', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wniosek',
            name='pracownik',
        ),
        migrations.AddField(
            model_name='wniosek',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
