# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='status',
            field=models.CharField(choices=[('1', 'Przyjęty'), ('2', 'Odrzucony'), ('3', 'Przetwarzanie')], default=3, max_length=1, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='pracownik',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pracownik', to='wnioski.Pracownik'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
