# Generated by Django 2.1.dev20171213075741 on 2017-12-16 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0006_auto_20171216_0105'),
        ('wnioski', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracownicyObiektyUprawnienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='wniosek',
            old_name='data',
            new_name='data_zlozenia',
        ),
        migrations.RenameField(
            model_name='wniosek',
            old_name='pracownik',
            new_name='dotyczy_pracownika',
        ),
        migrations.AlterField(
            model_name='historia',
            name='status',
            field=models.CharField(choices=[('1', 'Zatwierdzony'), ('2', 'Odrzucony'), ('3', 'Przetwarzanie')], default=3, max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='opis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uprawnienia',
            name='nazwa',
            field=models.CharField(max_length=255, verbose_name='Uprawnienie'),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='typ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wnioski.WniosekTyp'),
        ),
        migrations.AlterField(
            model_name='wniosektyp',
            name='typ',
            field=models.CharField(choices=[('1', 'Nadanie uprawnień'), ('2', 'Odebranie uprawnień'), ('3', 'Zmiana uprawnień')], default=1, max_length=1, verbose_name='Typ'),
        ),
        migrations.AddField(
            model_name='pracownicyobiektyuprawnienia',
            name='id_obiektu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Obiekt'),
        ),
        migrations.AddField(
            model_name='pracownicyobiektyuprawnienia',
            name='id_uprawnienia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Uprawnienia'),
        ),
        migrations.AddField(
            model_name='pracownicyobiektyuprawnienia',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_ex.Pracownik'),
        ),
    ]
