# Generated by Django 2.1.dev20171213075741 on 2017-12-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0002_auto_20171216_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wniosek',
            old_name='dotyczy_pracownika',
            new_name='pracownik',
        ),
    ]
