# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-20 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0002_auto_20170420_0921'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Obiekty_chronione',
            new_name='Obiekt',
        ),
        migrations.RenameModel(
            old_name='Pracownicy',
            new_name='Pracownik',
        ),
        migrations.RenameModel(
            old_name='Wnioski',
            new_name='Wniosek',
        ),
        migrations.RenameField(
            model_name='wniosek',
            old_name='id_obiektu',
            new_name='obiekt',
        ),
        migrations.RenameField(
            model_name='wniosek',
            old_name='id_prac_dot',
            new_name='prac_dot',
        ),
        migrations.RenameField(
            model_name='wniosek',
            old_name='id_prac_sklada',
            new_name='prac_sklada',
        ),
    ]
