# Generated by Django 2.1.dev20171202154135 on 2017-12-03 00:02

from django.db import migrations, models
import django.db.models.deletion
import wnioski.models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0002_auto_20170914_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='data_zatr',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='data_zwol',
        ),
        migrations.RemoveField(
            model_name='wniosektyp',
            name='typ',
        ),
        migrations.AddField(
            model_name='pracownik',
            name='czy_pracuje',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='numer_ax',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wniosektyp',
            name='nazwa',
            field=models.CharField(default='Zwykły', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data edycji'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='status',
            field=models.CharField(choices=[('1', 'Przyjęty'), ('2', 'Odrzucony'), ('3', 'Przetwarzanie')], default=3, max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='jednorg',
            name='id_jedn',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='jednorg',
            name='nazwa',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='nazwa',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='opis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='imie',
            field=models.CharField(max_length=81, validators=[wnioski.models.validate_name]),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='jedn_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wnioski.JednOrg', verbose_name='Jednostka organizacyjna'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nazwisko',
            field=models.CharField(max_length=55, validators=[wnioski.models.validate_surname]),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='rodzaj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wnioski.RodzajPracownika', verbose_name='Rodzaj pracownika'),
        ),
        migrations.AlterField(
            model_name='rodzajpracownika',
            name='nazwa',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='typobiektu',
            name='nazwa',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='uprawnienia',
            name='nazwa',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data złożenia'),
        ),
    ]
