# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0003_auto_20170420_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JednOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jedn', models.CharField(max_length=20)),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='RodzajPracownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TypObiektu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Uprawnienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='pracownik',
            name='data_zatr',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='data_zwol',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='email',
            field=models.EmailField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='haslo',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='login',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='szkolenie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wniosek',
            name='typ',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='jedn_org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.JednOrg'),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='nazwa',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='opis',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='obiekt',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.TypObiektu'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='imie',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nazwisko',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='data_zlo',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='historia',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Status'),
        ),
        migrations.AddField(
            model_name='historia',
            name='wniosek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wnioski.Wniosek'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='jedn_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wnioski.JednOrg'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='rodzaj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wnioski.RodzajPracownika'),
        ),
    ]
