# Generated by Django 2.1.dev20171213075741 on 2017-12-16 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0003_auto_20171216_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wniosek',
            old_name='data_zlozenia',
            new_name='data',
        ),
    ]
