# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0004_auto_20171216_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownicyobiektyuprawnienia',
            name='id_uprawnienia',
        ),
        migrations.AddField(
            model_name='pracownicyobiektyuprawnienia',
            name='uprawnienia',
            field=models.CharField(choices=[('1', 'Wgląd'), ('2', 'Tworzenie'), ('3', 'Modyfikacja'), ('4', 'Przetwarzanie na serwerze i w biurze'), ('5', 'Przechowywanie'), ('6', 'Usuwanie, niszczenie'), ('7', 'Udostępnianie, powierzanie, przesyłanie')], default='1', max_length=1, verbose_name='Uprawnienia'),
        ),
        migrations.AddField(
            model_name='wniosek',
            name='uprawnienia',
            field=models.CharField(choices=[('1', 'Wgląd'), ('2', 'Tworzenie'), ('3', 'Modyfikacja'), ('4', 'Przetwarzanie na serwerze i w biurze'), ('5', 'Przechowywanie'), ('6', 'Usuwanie, niszczenie'), ('7', 'Udostępnianie, powierzanie, przesyłanie')], default='1', max_length=1, verbose_name='Uprawnienia'),
        ),
        migrations.DeleteModel(
            name='Uprawnienia',
        ),
    ]
