# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0004_auto_20170423_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='data_zwol',
            field=models.DateField(null=True),
        ),
    ]
