# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0001_initial'),
        ('wnioski', '0004_auto_20180105_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='pracownik',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_ex.Pracownik'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historia',
            name='status',
            field=models.CharField(choices=[('1', 'Złożony'), ('2', 'LABI'), ('3', 'ABI'), ('4', 'AS'), ('5', 'Odrzucony')], default=1, max_length=1, verbose_name='Status'),
        ),
    ]
