# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0005_auto_20180105_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='pracownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_ex.Pracownik'),
        ),
    ]
