# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0005_auto_20170423_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='data_zwol',
            field=models.DateField(blank=True, null=True),
        ),
    ]
