# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0005_auto_20171216_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wniosek',
            name='typ',
            field=models.CharField(choices=[('1', 'Nadanie uprawnień'), ('2', 'Odebranie uprawnień'), ('3', 'Zmiana uprawnień')], default='1', max_length=1, verbose_name='Typ'),
        ),
        migrations.DeleteModel(
            name='WniosekTyp',
        ),
    ]
