# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 18:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0007_auto_20180106_1918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZatwierdzoneObiekty',
            new_name='ZatwierdzonePrzezAS',
        ),
    ]
