# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wnioski', '0008_auto_20170424_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='haslo',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='login',
        ),
        migrations.AddField(
            model_name='pracownik',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
