# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0008_auto_20180106_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='obiekt',
            name='czy_aktywny',
            field=models.BooleanField(default=True, verbose_name='Czy obiekt aktywny'),
        ),
    ]
