# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0009_auto_20170522_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='user',
        ),
        migrations.AddField(
            model_name='pracownik',
            name='haslo',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='login',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
