# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0010_zatwierdzoneprzezas_komentarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obiekt',
            name='nazwa',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
