# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0011_auto_20170523_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wniosektyp',
            name='typ',
            field=models.CharField(max_length=45),
        ),
    ]
