# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wnioski', '0012_auto_20170523_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='haslo',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='login',
        ),
        migrations.AddField(
            model_name='pracownik',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pracownik', to=settings.AUTH_USER_MODEL),
        ),
    ]
