# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0013_auto_20170528_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
