# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-07 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wnioski', '0015_auto_20170529_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='wniosek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wniosek', to='wnioski.Wniosek'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='login',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='data_zlo',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name=b'Data z\xc5\x82o.'),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='obiekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obiekt', to='wnioski.Obiekt'),
        ),
        migrations.AlterField(
            model_name='wniosek',
            name='prac_sklada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wnioski_sklada', to='wnioski.Pracownik', verbose_name=b'Sk\xc5\x82adaj\xc4\x85cy'),
        ),
    ]
