# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-05 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JednOrg',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_labi', models.BooleanField(default=False)),
                ('nazwa', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_ex.JednOrg')),
            ],
        ),
        migrations.CreateModel(
            name='Labi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jednostka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_ex.JednOrg')),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('login', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Login')),
                ('imie', models.CharField(max_length=90, verbose_name='Imie')),
                ('nazwisko', models.CharField(max_length=90, verbose_name='Nazwisko')),
                ('email', models.EmailField(max_length=60, verbose_name='Email')),
                ('numer_ax', models.CharField(max_length=6, null=True, unique=True)),
                ('czy_aktywny', models.BooleanField(default=True)),
                ('jedn_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_ex.JednOrg')),
            ],
        ),
        migrations.CreateModel(
            name='RodzajPracownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(default='Zwykły', max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pracownik',
            name='rodzaj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_ex.RodzajPracownika'),
        ),
        migrations.AddField(
            model_name='labi',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_ex.Pracownik'),
        ),
    ]
