# Generated by Django 2.1.dev20171202154135 on 2017-12-03 14:59

import auth_ex.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JednOrg',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nazwa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=81, validators=[auth_ex.models.validate_name])),
                ('nazwisko', models.CharField(max_length=55, validators=[auth_ex.models.validate_surname])),
                ('szkolenie', models.BooleanField(default=0)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('login', models.CharField(max_length=45, null=True, unique=True)),
                ('haslo', models.CharField(max_length=45, null=True)),
                ('numer_ax', models.CharField(max_length=6, null=True, unique=True)),
                ('czy_pracuje', models.BooleanField(default=1)),
                ('jedn_org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth_ex.JednOrg', verbose_name='Jedn. org.')),
            ],
        ),
        migrations.CreateModel(
            name='RodzajPracownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pracownik',
            name='rodzaj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_ex.RodzajPracownika', verbose_name='rodzaj'),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
