# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='czy_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pracownik',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Haslo'),
        ),
    ]
