# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jednorg',
            name='przodek',
            field=models.CharField(max_length=20, null=True, verbose_name='ID przodka'),
        ),
    ]
