# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0002_auto_20171206_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jednorg',
            name='przodek',
        ),
        migrations.AddField(
            model_name='jednorg',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_ex.JednOrg'),
        ),
    ]
