# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0002_auto_20180110_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='czy_user',
            field=models.BooleanField(default=False),
        ),
    ]
