# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0003_auto_20171206_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jednorg',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_ex.JednOrg'),
        ),
    ]
