# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0004_auto_20171206_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='labi',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='labi',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='labi',
            name='login',
            field=models.CharField(default='', max_length=60, verbose_name='login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pracownik',
            name='login',
            field=models.CharField(default='', max_length=60, unique=True, verbose_name='Login'),
            preserve_default=False,
        ),
    ]
