# Generated by Django 2.1.dev20171213075741 on 2017-12-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0005_auto_20171207_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jednorg',
            name='opis',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='aktywny',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='data_zat',
        ),
        migrations.RemoveField(
            model_name='pracownik',
            name='id',
        ),
        migrations.AddField(
            model_name='jednorg',
            name='nazwa',
            field=models.CharField(default='Wydział Matematyki i Informatyki', max_length=255, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='jednorg',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='labi',
            name='login',
            field=models.ForeignKey(on_delete='login', to='auth_ex.Pracownik'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='imie',
            field=models.CharField(max_length=90, verbose_name='Imie'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='login',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='nazwisko',
            field=models.CharField(max_length=90, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='rodzajpracownika',
            name='rodzaj',
            field=models.CharField(max_length=255),
        ),
    ]
