# Generated by Django 2.1.dev20171213075741 on 2017-12-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0006_auto_20171216_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jednorg',
            name='nazwa',
            field=models.CharField(default='Wydział Matematyki i Informatyki', max_length=255, verbose_name='Nazwa'),
        ),
    ]
