# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-16 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_ex', '0007_auto_20171216_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drzewo',
            name='jednostka',
        ),
        migrations.RemoveField(
            model_name='drzewo',
            name='labi',
        ),
        migrations.AlterField(
            model_name='jednorg',
            name='nazwa',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
        migrations.DeleteModel(
            name='Drzewo',
        ),
    ]
